version: 2.1

orbs:
  codacy: codacy/base@10.11.0

jobs:
  unit_test:
    docker:
      - image: cimg/go:1.18
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Run go test
          command: go test

workflows:
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          version_prefix: "v"
      - unit_test:
          requires:
            - codacy/checkout_and_version
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - unit_test
          filters:
            branches:
              only:
                - master
